#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: managers-repo-build
  namespace: galasa-tekton
spec:
  workspaces:
  - name: git-workspace
    optional: false
  params:
  - name: distBranch
    type: string
  - name: refspec
    type: string
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "true"
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: clone-managers
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/managers
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: managers
    workspaces:
     - name: output
       workspace: git-workspace
  - name: managers-compile
    taskRef:
      name: managers-repo-build
    runAfter:
    - clone-managers
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: extensionsSourceRepo
      value: http://maven-main-extensions.galasa-development.svc.cluster.local/galasadev/$(params.distBranch)/maven/extensions/
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-managers
    taskRef:
      name: recycle-deployment
    runAfter:
    - managers-compile
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-managers
