#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: managers-repo-build
  namespace: galasa-tekton
spec:
  workspaces:
  - name: git-workspace
    optional: false
    mountpath: /workspace/git
  params:
  - name: distBranch
    type: string
  - name: mavenCentralRepo
    type: string
    default: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
  - name: extensionsSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
  steps:
  - name: get-commit
    workingDir: /workspace/git/managers
    image: $(params.dockerRepo)/galasa/galasa-build
    script: |
      #!/bin/sh
      set +e
      COMMIT="$(git log --format="%H" -n 1)"
      echo $COMMIT > /workspace/git/managers/docker/managers.githash
      echo commit is $COMMIT
  - name: gradle-build
    workingDir: /workspace/git/managers/galasa-managers-parent
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - gradle
    - --no-daemon
    - --console 
    - plain
    - -PsourceMaven=$(params.extensionsSourceRepo)
    - -PcentralMaven=$(params.mavenCentralRepo)
    - -PtargetMaven=/workspace/git/managers/docker/repo
    - -PjacocoEnabled=$(params.jacocoEnabled)
    - -PisRelease=$(params.isRelease)
    - publish
    volumeMounts:
    - name: gpgkey
      mountPath: /opt/gradle/gradle-6.8.2/galasa.gpg
      subPath: galasa.gpg
    - name: gpggradle
      mountPath: /opt/gradle/gradle-6.8.2/gradle.properties
      subPath: gradle.properties
  - name: docker-build
    workingDir: /workspace/git/managers/docker
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/managers/docker
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-managers:$(params.distBranch)
    - --oci-layout-path=/workspace/git/managers/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - $(params.noPush)
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=branch=$(params.distBranch)
