#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi