#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
spec:
  selector:
    matchLabels:
      app: testdeployment
  template:
    metadata:
      labels:
        app: testdeployment
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: httpd
        image: "httpd:latest"
        ports:
        - containerPort: 80