#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: testservice
spec:
  selector: 
    app: testdeployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 