apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teststatefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeployment
  template:
    metadata:
      labels:
        app: testdeployment
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: httpd
        image: "httpd:latest"
        ports:
        - containerPort: 80