#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8-selenium-node-<RUNNAME>
  name: k8-selenium-node-<RUNNAME>
spec:
  type: NodePort
  ports:
    - name: endpoint
      port: 4444
      targetPort: 4444
      protocol: TCP
  selector:
    app: k8-selenium-node-<RUNNAME>